export const CREDENTIALS_API_NAME = 'joggAiCredentialsApi';

export const LOOKUP_RESOURCE = {
	name: 'Jogg.ai Lookup',
	value: 'lookup',
	operation: {
		LIST_VOICE: {
			name: 'Get My Voice',
			value: 'voice:list',
			description: 'Retrieve a list of your available voice with specified gender filter',
		},
		LIST_VISUAL_STYLE: {
			name: 'Get Visual Style',
			value: 'visualStyle:list',
			description: 'Get list of Visual Style',
		},
		LIST_TEMPLATE: {
			name: 'Get My Template',
			value: 'template:list',
			description: 'Get list of your custom templates',
		},
		LIST_MUSIC: {
			name: 'Get Music List from JoggAI',
			value: 'music:list',
			description: 'Get a list of jogg music',
		},
	},
};

export const ASSETS_RESOURCE = {
	name: 'Jogg.ai Assets',
	value: 'assets',
	operation: {
		AI_SCRIPTS: {
			name: 'AI Scripts',
			value: 'createScript',
			description: `Simply provide the product information or the product_id generated in the Upload URL to create product,
and you can create several different styles of product introduction scripts.If you do not provide the product_id,
then the product's name and description are required.`,
		},
		UPLOAD_MEDIA: {
			name: 'Upload Media',
			value: 'uploadFile',
			description:
				'Generate a signed URL for file upload. Use the sign_url obtained here to upload your file.',
		},
		GENERATE_AI_AVATAR_PHOTO: {
			name: 'Generate AI Avatar Photo',
			value: 'generateFromPhoto',
			description: 'Generate four photos based on the provided parameters',
		},
		GENERATE_AVATAR_NEW_LOOK_PHOTO: {
			name: 'Generate Avatar New Look Photo',
			value: 'generateNewLook',
			description:
				'Based on the provided photo, a new photo is generated by marrying the input parameters',
		},
		ADD_MOTION: {
			name: 'Add Motion',
			value: 'addMotion',
			description: 'Adds an motion for the specified Photo Avatar',
		},
		CHECK_PHOTO_GENERATION_STATUS: {
			name: 'Check Photo Generation Status',
			value: 'checkPhotoStatus',
			description: 'Check the generation status of the AI profile photo according to the photo ID',
		},
		CHECK_MOTION_GENERATION_STATUS: {
			name: 'Check Motion Generation Status',
			value: 'checkMotionStatus',
			description: 'Check the generation status of the Photo Avatar motion based on the motionID',
		},
	},
};

export const TEMPLATE_RESOURCE = {
	name: 'Jogg.ai Template',
	value: 'template',
	operation: {
		CREATE_VIDEO_FROM_TEMPLATE: {
			name: 'Create Video From Template',
			value: 'createVideoFromTemplate',
			description: 'Create video from Your Template',
		},
	},
};

export const TALKING_AVATAR_RESOURCE = {
	name: 'Talking Avatar',
	value: 'talkingAvatar',
	operation: {
		CREATE_TALKING_AVATAR_VIDEOS: {
			name: 'Create Talking Avatar Videos',
			value: 'createTalkingAvatar',
			description: 'Creates a talking avatar video with specified parameters',
		},
	},
};

export const URL_TO_VIDEO_RESOURCE = {
	name: 'URL / Product To Video',
	value: 'urlProductToVideo',
	operation: {
		UPLOAD_URL_TO_CREATE_PRODUCT: {
			name: 'Upload URL to Create Product',
			value: 'uploadUrlCreateProduct',
			description:
				'Get product information by crawling the provided URL or create a new product with provided information',
		},
		UPDATE_PRODUCT_INFORMATION: {
			name: 'Update Product Information',
			value: 'updateProductInformation',
			description: 'Optional step to update product details',
		},
		GENERATE_VIDEO_FROM_PRODUCT_INFORMATION: {
			name: 'Generate Video From Product Information',
			value: 'generateVideoFromProductInformation',
			description: 'Final step to generate the product video',
		},
		GENERATE_PREVIEW_VIDEO_FROM_PRODUCT_INFORMATION: {
			name: 'Generate Preview Video From Product Information',
			value: 'generatePreviewVideoFromProductInformation',
			description:
				'You can generate a preview video using the product_id obtained from the Upload URL to create a product',
		},
	},
};

export const GET_GENERATED_VIDEO_RESOURCE = {
	name: 'Get Generated Video',
	value: 'getGeneratedVideoAction',
	operation: {
		GET_GENERATED_VIDEO: {
			name: 'Get Generated Video',
			value: 'getGeneratedVideo',
			description: 'Get information about a specific project using its ID',
		},
	},
};

export const WEBHOOK_RESOURCE = {
	name: 'Webhook',
	value: 'webhook',
	operation: {
		LIST_WEBHOOK: {
			name: 'List of Webhook Endpoints',
			value: 'webhook:list',
			description: 'Get a list of configured webhook endpoints',
		},
		ADD_WEBHOOK: {
			name: 'Add a Webhook Endpoint',
			value: 'webhook:add',
			description: 'Add a new webhook endpoint configuration',
		},
		UPDATE_WEBHOOK: {
			name: 'Update a Webhook Endpoint',
			value: 'webhook:update',
			description: 'Update an existing webhook endpoint configuration',
		},
		DELETE_WEBHOOK: {
			name: 'Delete a Webhook Endpoint',
			value: 'webhook:delete',
			description: 'Delete an existing webhook endpoint',
		},
		EVENTS_WEBHOOK: {
			name: 'List of Available Webhook Events',
			value: 'webhook:events',
			description: 'Get a list of available webhook events',
		},
	},
};
